

CREATE TABLE PAYS (
	PAYS_ID		SMALLINT,
	NOM_PAYS		VARCHAR(30),
	CONSTRAINT PK_PAYS
		PRIMARY KEY (PAYS_ID)
);


CREATE TABLE REGION (
	REGION_ID		SMALLINT,
	NOM_REGION		VARCHAR(30),
	PAYS_ID		SMALLINT NOT NULL,
	CONSTRAINT FK_REGION_PAYS_ID FOREIGN KEY (PAYS_ID) REFERENCES PAYS(PAYS_ID),
	CONSTRAINT PK_REGION PRIMARY KEY (REGION_ID)
);

CREATE TABLE VILLE (
	VILLE_ID		SMALLINT,
	NOM_VILLE		VARCHAR(30),
	REGION_ID		SMALLINT NOT NULL,
	CONSTRAINT FK_VILLE_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID),
	CONSTRAINT PK_VILLE PRIMARY KEY (VILLE_ID)
);


CREATE TABLE OPERATEUR (
	OPERATEUR_ID		VARCHAR(2),
	NOM_OPERATEUR		VARCHAR(30),
	CHEF_ID			VARCHAR(2),
	CONSTRAINT PK_OPERATEUR PRIMARY KEY (OPERATEUR_ID)
);


CREATE TABLE TRANCHE_AGE (
	TRANCHE_AGE		VARCHAR(10),
	AGE_MIN		SMALLINT,
	AGE_MAX		SMALLINT,
	CONSTRAINT PK_TRANCHE_AGE  PRIMARY KEY (TRANCHE_AGE)
);

CREATE TABLE CLIENT (
	CLIENT_ID			VARCHAR(4),
	NOM_CLIENT			VARCHAR(20),
	PRENOM_CLIENT		VARCHAR(20),
	ADRESSE_RUE_CLIENT	VARCHAR(30),
	TEL_CLIENT			VARCHAR(15),
	PARRAIN_ID			VARCHAR(4) NULL, /* le client parrain */
	AGE				SMALLINT,
	VILLE_ID			 SMALLINT NOT NULL,
	OPERATEUR_ID		VARCHAR(2) NULL,
	CONSTRAINT FK_CLIENT_VILLE_ID FOREIGN KEY (VILLE_ID) REFERENCES VILLE(VILLE_ID),
	CONSTRAINT FK_CLIENT_OPERATEUR_ID FOREIGN KEY (OPERATEUR_ID) REFERENCES OPERATEUR(OPERATEUR_ID),
	CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID)
);


CREATE TABLE HOTEL (
	HOTEL_ID			INT,
	NOM_HOTEL			VARCHAR(30),
	VILLE_ID			SMALLINT NOT NULL,
	CONSTRAINT FK_HOTEL_VILLE_ID FOREIGN KEY (VILLE_ID) REFERENCES VILLE(VILLE_ID),
	CONSTRAINT PK_HOTEL PRIMARY KEY (HOTEL_ID)
);


CREATE TABLE RESERVATION (
	RESERVATION_ID		INT,
	DATE_DEB_RESERVATION	TIMESTAMP,
	NBNUITS_RESERVATION	TINYINT,
	CLIENT_ID			VARCHAR(4) NOT NULL,	
	HOTEL_ID			INT NOT NULL,
	CONSTRAINT FK_RESERVATION_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
	CONSTRAINT FK_RESERVATION_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID),
	CONSTRAINT PK_RESERVATION PRIMARY KEY (RESERVATION_ID)
);


CREATE TABLE PRODUIT (
	PRODUIT_ID			INT,
	NOM_PRODUIT			VARCHAR(30),
	PRIX_BASE_PRODUIT		DECIMAL(5,2),
	CONSTRAINT PK_PRODUIT 	PRIMARY KEY (PRODUIT_ID)
);


CREATE TABLE FACTURE (
	FACTURE_ID			INT,
	DATE_DEB_SEJOUR		TIMESTAMP,
	NBNUITS_SEJOUR			TINYINT,
	CLIENT_ID			VARCHAR(4) NOT NULL,	
	HOTEL_ID			INT NOT NULL,
	CONSTRAINT FK_FACTURE_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID),
	CONSTRAINT FK_FACTURE_HOTEL_ID FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID),
	CONSTRAINT PK_FACTURE PRIMARY KEY (FACTURE_ID)
);

CREATE TABLE LIGNE_FACTURE (
	FACTURE_ID			INT,
	PRODUIT_ID			INT,
	QUANTITE			SMALLINT,
	CONSTRAINT FK_LIGNE_FACTURE_FACTURE_ID FOREIGN KEY (FACTURE_ID) REFERENCES FACTURE(FACTURE_ID),
	CONSTRAINT FK_LIGNE_FACTURE_PRODUIT_ID FOREIGN KEY (PRODUIT_ID) REFERENCES PRODUIT(PRODUIT_ID),
	CONSTRAINT PK_LIGNE_FACTURE PRIMARY KEY (FACTURE_ID,PRODUIT_ID)
);



INSERT INTO PAYS (PAYS_ID,NOM_PAYS)
	VALUES ('1','Etats-Unis');
INSERT INTO PAYS (PAYS_ID,NOM_PAYS)
	VALUES ('2','France');
INSERT INTO PAYS (PAYS_ID,NOM_PAYS)
	VALUES ('3','Grande Bretagne');
INSERT INTO PAYS (PAYS_ID,NOM_PAYS)
	VALUES ('4','Allemagne');
INSERT INTO PAYS (PAYS_ID,NOM_PAYS)
	VALUES ('5','Japon');
INSERT INTO PAYS (PAYS_ID,NOM_PAYS)
	VALUES ('6','Australie');
INSERT INTO PAYS (PAYS_ID,NOM_PAYS)
	VALUES ('7','Holland');


INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
	VALUES(20,'South',1);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
	VALUES(21,'West',1);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
	VALUES(22,'East Coast',1);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
	VALUES(23,'Mid West',1);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
	VALUES(30,'Mid West',1);

INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(31,	'French Alps',2);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(32,	'Provence',	2);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(33,	'Normandy',	2);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(40,	'Wales',	3);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(41,	'Scotland',	3);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(42,	'Northern Ireland',3);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(43,	'England',	3);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(50,	'South Holland',	7);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(51,	'North Holland',	7);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(60,	'Ruhr',	4);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(61,	'Bavaria',	4);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(62,	'East Germany',	4);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(70,	'South Wales',	6);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(71,	'Victoria',	6);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(72,	'Queensland',6);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(80,	'East Japan',5);
INSERT INTO REGION (REGION_ID,NOM_REGION,PAYS_ID)
VALUES(81,	'West Japan',5);



INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(10,	'Houston',	20);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(11,	'Dallas'	,20);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(12,	'San Francisco',	21);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(13,	'Los Angeles',	21);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(14,	'San Diego',	21);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(15,	'Chicago',	23);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(16,	'Memphis',	23);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(17,	'New York City',	22);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(18,	'Boston'	,22);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(19,	'Washington D.C.',	22);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(20,	'Paris',	30);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(21,	'Versailles',	30);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(22,	'Fontainebleau',	30);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(23,	'Lyon'	,31);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(24,	'Grenoble'	,31);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(25,	'Albertville',	31);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(27,	'Nice'	,32);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(28,	'Marseilles',	32);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(29,	'Bordeaux'	,32);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(30,	'Swansea'	,40);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(31,	'Glasgow'	,41);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(32,	'Edinburgh'	,41);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(33,	'Belfast'	,42);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(34,	'Londonderry',	42);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(35,	'London'	,43);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(36,	'Oxford'	,43);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(37,	'Manchester',	43);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(38,	'Cardiff'	,40);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(40,	'Amsterdam'	,51);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(41,	'Utrecht'	,51);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(42,	'Rotterdam'	,50);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(43,	'Eindhoven'	,50);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(50,	'Dusseldorf',	60);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(51,	'Cologne'	,60);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(52,	'Munich'	,61);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(53,	'Dresden'	,62);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(54,	'Magdeburg'	,62);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(55,	'Berlin'	,62);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(56,	'Augsburg'	,61);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(60,	'Sidney'	,70);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(61,	'Canberra'	,70);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(62,	'Melbourne'	,71);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(63,	'Brisbane'	,72);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(64,	'Gold Coast',	72);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(70,	'Tokyo'	,80);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(71,	'Yokohama'	,80);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(72,	'Osaka'	,81);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(73,	'Kyoto'	,81);
INSERT INTO VILLE (VILLE_ID,NOM_VILLE,REGION_ID)
VALUES(74,	'Kobe'	,81);

INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (10,	'Hamilton',32);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (11,	'Andersen',32);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (12,	'Galagers',32);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (13,	'Jeferson',32);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (20,	'Daumesnil',10);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (21,	'Barrot',12);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (22,	'Carlil',10);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (30,	'Moore',10);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (31,	'Edwood',20);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (32,	'Keegan',NULL);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (40,	'Bauman',20);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (41,	'Fischer',20);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (42,	'Schmidt',20);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (50,	'Ishimoto',21);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (51,	'Nagata',11);
INSERT INTO OPERATEUR (OPERATEUR_ID,NOM_OPERATEUR,CHEF_ID)
VALUES (52,	'Kudo',20);


INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	101	,	'Brendt'	,	'Paul'	,	'10 Jasper Blvd.'	,	'(212); 555 2146'	,	NULL	,	19	,	17	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	102	,	'McCarthy'	,	'Robin'	,	'27 Pasadena Drive'	,	'(214); 555 3075'	,	104	,	29	,	11	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	103	,	'Travis'	,	'Peter'	,	'7835 Hartford Drive'	,	'(510); 555 4448'	,	NULL	,	34	,	12	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	104	,	'Larson'	,	'Joe'	,	'87 Carmel Blvd.'	,	'(213); 555 5095'	,	NULL	,	45	,	13	,	12	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	105	,	'Goldschmidt'	,	'Tony'	,	'91 Torre drive'	,	'(619); 555 6529'	,	NULL	,	55	,	14	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	106	,	'Baker'	,	'William'	,	'2890 Grant Avenue'	,	'(312); 555 7040'	,	104	,	64	,	15	,	12	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	107	,	'Swenson'	,	'Jack'	,	'64 Imagination Drive'	,	'(202); 555 8125'	,	NULL	,	74	,	19	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	201	,	'Sartois'	,	'Jean'	,	'71 rue Rousseau'	,	'79 23 26 23'	,	NULL	,	19	,	25	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	202	,	'Michaud'	,	'Philippe'	,	'197 impasse Renoir'	,	'78 21 86 20'	,	204	,	22	,	23	,	22	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	203	,	'Robert'	,	'Christian'	,	'1rue Cezanne'	,	'42 25 27 29'	,	NULL	,	38	,	28	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	204	,	'Martin'	,	'Christine'	,	'12 allee Victor Hugo'	,	'25 26 46 26'	,	NULL	,	42	,	24	,	21	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	205	,	'Piaget'	,	'Luc'	,	'38 allee des Saules'	,	'53 42 24 28'	,	NULL	,	56	,	29	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	206	,	'Gentil'	,	'Michele'	,	'17montee des Chenes'	,	'65 62 26 13'	,	204	,	67	,	25	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	207	,	'Dupont'	,	'Marie-Chantale'	,	'37 rue Murat'	,	'46 72 23 53'	,	NULL	,	72	,	20	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	301	,	'Edwards'	,	'Caroline'	,	'68 Downing Street'	,	'243 867945'	,	NULL	,	18	,	35	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	302	,	'Marlow'	,	'Justin'	,	'290 Yorkshire Drive'	,	'653 643634'	,	304	,	29	,	32	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	303	,	'Wilson'	,	'John'	,	'28 Sutton Row'	,	'158 746231'	,	NULL	,	34	,	33	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	304	,	'McCartney'	,	'George'	,	'45 Glenthorne Road'	,	'323 768678'	,	NULL	,	47	,	34	,	31	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	305	,	'Keegan'	,	'Hariett'	,	'10 Hamilton Park'	,	'566 344643'	,	NULL	,	56	,	35	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	306	,	'Jones'	,	'Mary'	,	'34 Apple Grove'	,	'143 546456'	,	NULL	,	68	,	36	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	307	,	'Hopkins'	,	'Priscilla'	,	'The Gables'	,	'634 634643'	,	NULL	,	73	,	38	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	401	,	'Diemers'	,	'Erika'	,	'WiesenstraDFe 40'	,	'23 5345'	,	NULL	,	18	,	51	,	41	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	402	,	'Schiller'	,	'Jurgen'	,	'Auf dem Rain 4'	,	'14 2352'	,	404	,	24	,	52	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	403	,	'Durnstein'	,	'Adolph'	,	'Thomashof 22'	,	'74 5464'	,	NULL	,	36	,	53	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	404	,	'Weimar'	,	'Hans'	,	'Goethering 33'	,	'34 6636'	,	NULL	,	45	,	54	,	41	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	405	,	'Schultz'	,	'Herbert'	,	'Am Holzbach 17'	,	'25 6346'	,	NULL	,	59	,	55	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	406	,	'Titzman'	,	'Silke'	,	'Berliner Ring 56'	,	'23 5463'	,	NULL	,	63	,	56	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	407	,	'Reinman'	,	'Heineke'	,	'YorkstraDFe 75'	,	'23 4646'	,	NULL	,	72	,	55	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	501	,	'Arai'	,	'Toshihijo'	,	'941 Toyota Ave'	,	'3478 4597'	,	NULL	,	18	,	70	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	502	,	'Kamata'	,	'Mariko'	,	'70 Kiroto Street'	,	'5768 7462'	,	504	,	24	,	71	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	503	,	'Kamimura'	,	'Satoru'	,	'34 Kawasaki Avenue'	,	'2647 5684'	,	NULL	,	38	,	72	,	51	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	504	,	'Makino'	,	'Tatsuo'	,	'2435 Toyota Ave'	,	'3441 3486'	,	NULL	,	45	,	70	,	50	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	505	,	'Mukumoto'	,	'Masayuki'	,	'59 Yamamoto Blvd'	,	'3482 7691'	,	NULL	,	59	,	73	,	NULL	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	506	,	'Oneda'	,	'Kenji'	,	'94 Toyota Blvd'	,	'5183 9463'	,	504	,	68	,	70	,	50	);
INSERT INTO CLIENT (CLIENT_ID,NOM_CLIENT,PRENOM_CLIENT,ADRESSE_RUE_CLIENT,TEL_CLIENT,PARRAIN_ID,AGE,VILLE_ID,OPERATEUR_ID) VALUES
(	507	,	'Okumura'	,	'Isao'	,	'3 Toyota Ave'	,	'4892 8371'	,	NULL	,	74	,	74	,	NULL	);


INSERT INTO TRANCHE_AGE (TRANCHE_AGE,AGE_MIN,AGE_MAX)
VALUES ('18-30',18,30);
INSERT INTO TRANCHE_AGE (TRANCHE_AGE,AGE_MIN,AGE_MAX)
VALUES ('30-60',31,60);
INSERT INTO TRANCHE_AGE (TRANCHE_AGE,AGE_MIN,AGE_MAX)
VALUES ('60 et +',61,100);



INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	1	,	'Hotel Le bat'	,	10	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	2	,	'La gare'	,	11	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	3	,	'Hotel Suite'	,	11	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	4	,	'La suite'	,	12	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	5 	,	'Chez Robert'	,	12	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	6	,	'Poolside'	,	15	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	7	,	'Activities+'	,	16	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	8	,	'La belle'	,	17	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	9	,	'Chez Robert'	,	23	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	10	,	'Hotel Room 2000'	,	31	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	11	,	'Le royal'	,	20	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	12	,	'Hotel et Suite'	,	30	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	13	,	'Le Paris'	,	32);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	14	,	'La belle ville'	,	30	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	15	,	'Le normandie'	,	30	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	16	,	'Hotel Room'	,	40	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	17	,	'Excursion'	,	41	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	18	,	'Hotel 2000'	,	50	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	19	,	'Hotel +'	,	50	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	20	,	'Hotel 2000'	,	60	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	21	,	'Hotel ++'	,	61	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	22	,	'Le Paris'	,	62	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	23	,	'Chez Michel'	,	63	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	24	,	'Mon Hotel'	,	64	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	25	,	'Le royal'	,	70	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	26	,	'La belle'	,	71	);
INSERT INTO HOTEL (HOTEL_ID,NOM_HOTEL,VILLE_ID) VALUES
(	27	,	'Hotel +++'	,	72	);




INSERT INTO PRODUIT (PRODUIT_ID,NOM_PRODUIT,PRIX_BASE_PRODUIT)
VALUES (1,'Nuit chambre simple',230);
INSERT INTO PRODUIT (PRODUIT_ID,NOM_PRODUIT,PRIX_BASE_PRODUIT)
VALUES (2,'Nuit chambre double',280);
INSERT INTO PRODUIT (PRODUIT_ID,NOM_PRODUIT,PRIX_BASE_PRODUIT)
VALUES (3,'Petit dE9jeuner',30);
INSERT INTO PRODUIT (PRODUIT_ID,NOM_PRODUIT,PRIX_BASE_PRODUIT)
VALUES (4,'TE9lephone',2);


INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6000	,	 strptime('21/10/1998', '%d/%m/%Y')	,	3	,	101	,	10	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6050	,	 strptime('14/11/1998', '%d/%m/%Y')	,	2	,	202	,	11	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6100	,	 strptime('07/12/1998', '%d/%m/%Y')	,	1	,	303	,	1	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6150	,	 strptime('11/10/1998', '%d/%m/%Y')	,	5	,	404	,	5	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6200	,	 strptime('19/11/1998', '%d/%m/%Y')	,	10	,	505	,	6	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6250	,	 strptime('12/01/1999', '%d/%m/%Y')	,	11	,	106	,	8	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6300	,	 strptime('15/02/1999', '%d/%m/%Y')	,	2	,	207	,	11	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6350	,	 strptime('24/03/1999', '%d/%m/%Y')	,	1	,	301	,	1	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6400	,	 strptime('07/01/1999', '%d/%m/%Y')	,	5	,	402	,	5	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6450	,	 strptime('28/01/1999', '%d/%m/%Y')	,	3	,	503	,	4	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6500	,	 strptime('05/04/1999', '%d/%m/%Y')	,	1	,	104	,	8	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6550	,	 strptime('20/05/1999', '%d/%m/%Y')	,	2	,	205	,	12	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6600	,	 strptime('07/06/1999', '%d/%m/%Y')	,	5	,	306	,	11	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6650	,	 strptime('22/04/1999', '%d/%m/%Y')	,	4	,	407	,	25	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6700	,	 strptime('28/04/1999', '%d/%m/%Y')	,	3	,	502	,	21	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6750	,	 strptime('30/06/1999', '%d/%m/%Y')	,	8	,	103	,	20	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6800	,	 strptime('03/08/1999', '%d/%m/%Y')	,	9	,	204	,	10	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6850	,	 strptime('11/09/1999', '%d/%m/%Y')	,	4	,	305	,	11	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6900	,	 strptime('25/07/1999', '%d/%m/%Y')	,	2	,	406	,	12	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	6950	,	 strptime('07/08/1999', '%d/%m/%Y')	,	1	,	507	,	14	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7000	,	 strptime('15/10/1998', '%d/%m/%Y')	,	1	,	102	,	15	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7001	,	 strptime('05/11/1998', '%d/%m/%Y')	,	5	,	203	,	16	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7050	,	 strptime('07/12/1998', '%d/%m/%Y')	,	4	,	304	,	17	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7051	,	 strptime('08/10/1998', '%d/%m/%Y')	,	3	,	405	,	18	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7100	,	 strptime('18/11/1998', '%d/%m/%Y')	,	8	,	506	,	14	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7101	,	 strptime('17/12/1999', '%d/%m/%Y')	,	9	,	107	,	15	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7150	,	 strptime('11/10/1999', '%d/%m/%Y')	,	4	,	202	,	20	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7151	,	 strptime('11/11/1999', '%d/%m/%Y')	,	8	,	303	,	21	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7200	,	 strptime('04/11/1999', '%d/%m/%Y')	,	2	,	404	,	22	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7201	,	 strptime('02/12/1999', '%d/%m/%Y')	,	3	,	505	,	16	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7250	,	 strptime('03/01/2000', '%d/%m/%Y')	,	6	,	106	,	17	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7251	,	 strptime('02/02/2000', '%d/%m/%Y')	,	5	,	207	,	18	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7300	,	 strptime('16/02/2000', '%d/%m/%Y')	,	4	,	302	,	14	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7301	,	 strptime('16/02/2000', '%d/%m/%Y')	,	8	,	403	,	15	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7350	,	 strptime('26/02/2000', '%d/%m/%Y')	,	8	,	504	,	16	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7351	,	 strptime('27/12/1999', '%d/%m/%Y')	,	3	,	105	,	17	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7400	,	 strptime('18/01/2000', '%d/%m/%Y')	,	6	,	206	,	18	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7401	,	 strptime('17/02/2000', '%d/%m/%Y')	,	5	,	307	,	14	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7450	,	 strptime('09/02/2000', '%d/%m/%Y')	,	4	,	402	,	15	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7451	,	 strptime('11/03/2000', '%d/%m/%Y')	,	8	,	503	,	20	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7500	,	 strptime('31/03/1999', '%d/%m/%Y')	,	9	,	104	,	21	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7501	,	 strptime('01/05/1999', '%d/%m/%Y')	,	4	,	204	,	22	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7550	,	 strptime('09/05/1999', '%d/%m/%Y')	,	8	,	306	,	23	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7551	,	 strptime('09/06/1999', '%d/%m/%Y')	,	2	,	407	,	24	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7600	,	 strptime('04/06/2000', '%d/%m/%Y')	,	3	,	502	,	25	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7601	,	 strptime('03/04/2000', '%d/%m/%Y')	,	6	,	103	,	26	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7650	,	 strptime('30/03/2000', '%d/%m/%Y')	,	5	,	204	,	1	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7651	,	 strptime('30/04/2001', '%d/%m/%Y')	,	1	,	305	,	5	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7700	,	 strptime('21/05/2001', '%d/%m/%Y')	,	1	,	406	,	5	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7701	,	 strptime('21/06/2001', '%d/%m/%Y')	,	1	,	507	,	4	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7750	,	 strptime('19/07/2001', '%d/%m/%Y')	,	1	,	102	,	3	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7751	,	 strptime('19/08/2001', '%d/%m/%Y')	,	12	,	203	,	5	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7850	,	 strptime('03/09/2001', '%d/%m/%Y')	,	3	,	304	,	4	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7851	,	 strptime('04/07/2001', '%d/%m/%Y')	,	2	,	405	,	5	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7900	,	 strptime('10/07/2001', '%d/%m/%Y')	,	1	,	506	,	4	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7901	,	 strptime('10/08/2001', '%d/%m/%Y')	,	40	,	107	,	3	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7950	,	 strptime('29/07/2001', '%d/%m/%Y')	,	9	,	202	,	8	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	7951	,	 strptime('28/08/2001', '%d/%m/%Y')	,	8	,	303	,	8	);
INSERT INTO RESERVATION (RESERVATION_ID,DATE_DEB_RESERVATION,NBNUITS_RESERVATION,CLIENT_ID,HOTEL_ID) VALUES
(	8000	,	 strptime('02/10/2000', '%d/%m/%Y')	,	9	,	404	,	2	);



INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6000	,	 strptime('21/10/1998', '%d/%m/%Y')	,	3	,	101	,	10	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6050	,	 strptime('14/11/1998', '%d/%m/%Y')	,	2	,	202	,	11	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6051	,	 strptime('20/11/1998', '%d/%m/%Y')	,	3	,	202	,	12	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6100	,	 strptime('07/12/1998', '%d/%m/%Y')	,	1	,	303	,	1	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6150	,	 strptime('11/10/1998', '%d/%m/%Y')	,	5	,	404	,	5	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6200	,	 strptime('19/11/1998', '%d/%m/%Y')	,	10	,	505	,	6	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6250	,	 strptime('12/01/1999', '%d/%m/%Y')	,	11	,	106	,	8	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6300	,	 strptime('15/02/1999', '%d/%m/%Y')	,	2	,	207	,	10	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6350	,	 strptime('24/03/1999', '%d/%m/%Y')	,	1	,	301	,	1	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6400	,	 strptime('07/01/1999', '%d/%m/%Y')	,	5	,	402	,	5	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6450	,	 strptime('28/01/1999', '%d/%m/%Y')	,	3	,	503	,	4	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6500	,	 strptime('05/04/1999', '%d/%m/%Y')	,	1	,	104	,	8	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6550	,	 strptime('20/05/1999', '%d/%m/%Y')	,	2	,	205	,	12	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6600	,	 strptime('07/06/1999', '%d/%m/%Y')	,	5	,	306	,	14); 
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6650	,	 strptime('22/04/1999', '%d/%m/%Y')	,	4	,	407	,	25	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6700	,	 strptime('28/04/1999', '%d/%m/%Y')	,	3	,	502	,	21	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6750	,	 strptime('30/06/1999', '%d/%m/%Y')	,	8	,	103	,	20	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6800	,	 strptime('03/08/1999', '%d/%m/%Y')	,	9	,	204	,	13	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6850	,	 strptime('11/09/1999', '%d/%m/%Y')	,	4	,	305	,	11	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6900	,	 strptime('25/07/1999', '%d/%m/%Y')	,	2	,	406	,	12	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	6950	,	 strptime('07/08/1999', '%d/%m/%Y')	,	1	,	507	,	14	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7000	,	 strptime('15/10/1998', '%d/%m/%Y')	,	1	,	102	,	15	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7001	,	 strptime('05/11/1998', '%d/%m/%Y')	,	5	,	203	,	14	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7050	,	 strptime('07/12/1998', '%d/%m/%Y')	,	4	,	304	,	17	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7051	,	 strptime('08/10/1998', '%d/%m/%Y')	,	3	,	405	,	18	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7100	,	 strptime('18/11/1998', '%d/%m/%Y')	,	8	,	506	,	14	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7101	,	 strptime('17/12/1999', '%d/%m/%Y')	,	9	,	107	,	15	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7150	,	 strptime('11/10/1999', '%d/%m/%Y')	,	4	,	202	,	20	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7151	,	 strptime('11/11/1999', '%d/%m/%Y')	,	8	,	303	,	21	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7200	,	 strptime('04/11/1999', '%d/%m/%Y')	,	2	,	404	,	22	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7201	,	 strptime('02/12/1999', '%d/%m/%Y')	,	3	,	505	,	16	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7250	,	 strptime('03/01/2000', '%d/%m/%Y')	,	6	,	106	,	17	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7251	,	 strptime('02/02/2000', '%d/%m/%Y')	,	5	,	207	,	18	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7300	,	 strptime('16/02/2000', '%d/%m/%Y')	,	4	,	302	,	14	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7301	,	 strptime('16/02/2000', '%d/%m/%Y')	,	8	,	403	,	15	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7350	,	 strptime('26/02/2000', '%d/%m/%Y')	,	8	,	504	,	16	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7351	,	 strptime('27/12/1999', '%d/%m/%Y')	,	3	,	105	,	17	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7400	,	 strptime('18/01/2000', '%d/%m/%Y')	,	6	,	206	,	18	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7401	,	 strptime('17/02/2000', '%d/%m/%Y')	,	5	,	307	,	14	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7450	,	 strptime('09/02/2000', '%d/%m/%Y')	,	4	,	402	,	15	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7451	,	 strptime('11/03/2000', '%d/%m/%Y')	,	8	,	503	,	20	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7500	,	 strptime('31/03/1999', '%d/%m/%Y')	,	9	,	104	,	21	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7501	,	 strptime('01/05/1999', '%d/%m/%Y')	,	2	,	205	,	22	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7550	,	 strptime('09/05/1999', '%d/%m/%Y')	,	8	,	306	,	23	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7551	,	 strptime('09/06/1999', '%d/%m/%Y')	,	2	,	407	,	24	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7600	,	 strptime('04/06/2000', '%d/%m/%Y')	,	3	,	502	,	25	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7601	,	 strptime('06/04/2000', '%d/%m/%Y')	,	5	,	103	,	26	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7650	,	 strptime('30/03/2000', '%d/%m/%Y')	,	4	,	204	,	1	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7651	,	 strptime('30/04/2001', '%d/%m/%Y')	,	1	,	305	,	5	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7700	,	 strptime('21/05/2001', '%d/%m/%Y')	,	1	,	406	,	5	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7701	,	 strptime('21/06/2001', '%d/%m/%Y')	,	1	,	507	,	4	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7750	,	 strptime('22/07/2001', '%d/%m/%Y')	,	8	,	102	,	3	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7751	,	 strptime('19/08/2001', '%d/%m/%Y')	,	12	,	203	,	5	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7850	,	 strptime('03/09/2001', '%d/%m/%Y')	,	3	,	304	,	4	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7851	,	 strptime('04/07/2001', '%d/%m/%Y')	,	2	,	405	,	5	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7900	,	 strptime('10/07/2001', '%d/%m/%Y')	,	1	,	506	,	4	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7901	,	 strptime('10/08/2001', '%d/%m/%Y')	,	40	,	107	,	3	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7950	,	 strptime('29/07/2001', '%d/%m/%Y')	,	9	,	202	,	8	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7951	,	 strptime('28/08/2001', '%d/%m/%Y')	,	4	,	303	,	8	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7952	,	 strptime('28/09/2001', '%d/%m/%Y')	,	6	,	303	,	8	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	7953	,	 strptime('1/10/2001', '%d/%m/%Y')	,	5	,	303	,	8	);
INSERT INTO FACTURE (FACTURE_ID,DATE_DEB_SEJOUR,NBNUITS_SEJOUR,CLIENT_ID,HOTEL_ID) VALUES
(	8000	,	 strptime('02/10/2000', '%d/%m/%Y')	,	9	,	404	,	2	);




INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6000	,	3	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6000	,	3	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6000	,	10	  , 4);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6050	,	2	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6051	,	3	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6100	,	1	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6150	,5	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6150	,4	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6200	,10	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6250	,11	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6300	,2	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6300	,2	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6350	,1	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6400	,5	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6400	,5	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6450	,3	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6500	,1	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6550	,2	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6600	,5	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6600	,4	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6600	,20	  , 4);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6650	,4	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6700	,3	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6750	,8	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6800	,	9	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6850	,4	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6850	,4	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6850	,15	  , 4);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6900	,2	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	6950	,1	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7000	,1	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7001	,5	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7050	,4	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7051	,3	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7100	,8	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7101	,9	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7101	,9	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7150	,4	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7151	,8	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7151	,8	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7200	,2	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7200	,2	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7201	,3	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7250	,6	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7251	,5	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7300	,4	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7300	,2	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7301	,8	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7350	,8	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7350	,7	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7351	,3	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7400	,6	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7401	,5	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7450	,4	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7451	,8	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7500	,9	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7501	,2	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7550	,8	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7550	,8	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7551	,2	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7600	,3	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7601	,5	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7601	,5	  , 3);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7650	,4	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7651	,1	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7700	,1	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7701	,1	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7750	,8	  , 2);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7751	,12	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7850	,3	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7851	,	2	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7900	,1	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7901	,40	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7950	,	9	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7951	,4	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7952	,6	  , 1);
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	7953	,5  	  , 1);	
INSERT INTO LIGNE_FACTURE (FACTURE_ID,QUANTITE,PRODUIT_ID) VALUES
(	8000	,9         , 1);






